[package]
name = "ownership-rust"
version = "0.1.0"
authors = ["Goran PjevicÌ <67331732+goranpjevic@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
